-- Migration 003 — table de référence pour les ingrédients et mesures
-- Permet de mémoriser les valeurs ajoutées par l'utilisateur et de les gérer
-- depuis la page Paramètres.

create table if not exists reference_items (
  id uuid primary key default gen_random_uuid(),
  type text not null check (type in ('ingredient', 'unit')),
  name text not null,
  created_at timestamptz not null default now(),
  unique (type, name)
);

alter table reference_items enable row level security;

drop policy if exists "Allow all on reference_items" on reference_items;
create policy "Allow all on reference_items" on reference_items for all using (true) with check (true);

insert into reference_items (type, name) values
  ('ingredient', 'ail'),
  ('ingredient', 'artichaut'),
  ('ingredient', 'asperge'),
  ('ingredient', 'aubergine'),
  ('ingredient', 'betterave'),
  ('ingredient', 'blette'),
  ('ingredient', 'brocoli'),
  ('ingredient', 'carotte'),
  ('ingredient', 'céleri branche'),
  ('ingredient', 'céleri rave'),
  ('ingredient', 'champignon de Paris'),
  ('ingredient', 'champignon shiitake'),
  ('ingredient', 'châtaigne'),
  ('ingredient', 'chou'),
  ('ingredient', 'chou blanc'),
  ('ingredient', 'chou chinois'),
  ('ingredient', 'chou de Bruxelles'),
  ('ingredient', 'chou frisé'),
  ('ingredient', 'chou rouge'),
  ('ingredient', 'chou-fleur'),
  ('ingredient', 'ciboule'),
  ('ingredient', 'citrouille'),
  ('ingredient', 'concombre'),
  ('ingredient', 'cornichon'),
  ('ingredient', 'courge butternut'),
  ('ingredient', 'courge spaghetti'),
  ('ingredient', 'courgette'),
  ('ingredient', 'cresson'),
  ('ingredient', 'échalote'),
  ('ingredient', 'endive'),
  ('ingredient', 'épinard'),
  ('ingredient', 'fenouil'),
  ('ingredient', 'gingembre'),
  ('ingredient', 'haricot beurre'),
  ('ingredient', 'haricot rouge'),
  ('ingredient', 'haricot vert'),
  ('ingredient', 'igname'),
  ('ingredient', 'laitue'),
  ('ingredient', 'maïs'),
  ('ingredient', 'manioc'),
  ('ingredient', 'navet'),
  ('ingredient', 'oignon'),
  ('ingredient', 'oignon blanc'),
  ('ingredient', 'oignon jaune'),
  ('ingredient', 'oignon rouge'),
  ('ingredient', 'olive noire'),
  ('ingredient', 'olive verte'),
  ('ingredient', 'oseille'),
  ('ingredient', 'panais'),
  ('ingredient', 'patate douce'),
  ('ingredient', 'persil plat'),
  ('ingredient', 'petit pois'),
  ('ingredient', 'piment'),
  ('ingredient', 'piment doux'),
  ('ingredient', 'poireau'),
  ('ingredient', 'pois mange-tout'),
  ('ingredient', 'poivron jaune'),
  ('ingredient', 'poivron rouge'),
  ('ingredient', 'poivron vert'),
  ('ingredient', 'pomme de terre'),
  ('ingredient', 'potimarron'),
  ('ingredient', 'potiron'),
  ('ingredient', 'radis'),
  ('ingredient', 'radis noir'),
  ('ingredient', 'raifort'),
  ('ingredient', 'rhubarbe'),
  ('ingredient', 'roquette'),
  ('ingredient', 'rutabaga'),
  ('ingredient', 'salade batavia'),
  ('ingredient', 'salade iceberg'),
  ('ingredient', 'salade romaine'),
  ('ingredient', 'salsifis'),
  ('ingredient', 'tomate'),
  ('ingredient', 'tomate cerise'),
  ('ingredient', 'topinambour'),
  ('ingredient', 'truffe'),
  ('ingredient', 'abricot'),
  ('ingredient', 'ananas'),
  ('ingredient', 'avocat'),
  ('ingredient', 'banane'),
  ('ingredient', 'bergamote'),
  ('ingredient', 'cassis'),
  ('ingredient', 'cerise'),
  ('ingredient', 'citron'),
  ('ingredient', 'citron vert'),
  ('ingredient', 'clémentine'),
  ('ingredient', 'coing'),
  ('ingredient', 'corossol'),
  ('ingredient', 'datte'),
  ('ingredient', 'figue'),
  ('ingredient', 'fraise'),
  ('ingredient', 'framboise'),
  ('ingredient', 'fruit de la passion'),
  ('ingredient', 'goyave'),
  ('ingredient', 'grenade'),
  ('ingredient', 'groseille'),
  ('ingredient', 'kaki'),
  ('ingredient', 'kiwi'),
  ('ingredient', 'kumquat'),
  ('ingredient', 'litchi'),
  ('ingredient', 'mandarine'),
  ('ingredient', 'mangue'),
  ('ingredient', 'melon'),
  ('ingredient', 'mirabelle'),
  ('ingredient', 'mûre'),
  ('ingredient', 'myrtille'),
  ('ingredient', 'nectarine'),
  ('ingredient', 'noix de coco'),
  ('ingredient', 'orange'),
  ('ingredient', 'pamplemousse'),
  ('ingredient', 'papaye'),
  ('ingredient', 'pastèque'),
  ('ingredient', 'pêche'),
  ('ingredient', 'physalis'),
  ('ingredient', 'poire'),
  ('ingredient', 'pomme'),
  ('ingredient', 'prune'),
  ('ingredient', 'pruneau'),
  ('ingredient', 'quetsche'),
  ('ingredient', 'raisin'),
  ('ingredient', 'raisin sec'),
  ('ingredient', 'tamarin'),
  ('ingredient', 'agneau'),
  ('ingredient', 'andouillette'),
  ('ingredient', 'bacon'),
  ('ingredient', 'blanc de poulet'),
  ('ingredient', 'boeuf haché'),
  ('ingredient', 'boudin noir'),
  ('ingredient', 'canard'),
  ('ingredient', 'chair à saucisse'),
  ('ingredient', 'chorizo'),
  ('ingredient', 'côte de porc'),
  ('ingredient', 'cuisse de poulet'),
  ('ingredient', 'dinde'),
  ('ingredient', 'entrecôte'),
  ('ingredient', 'escalope de veau'),
  ('ingredient', 'foie gras'),
  ('ingredient', 'gigot d''agneau'),
  ('ingredient', 'jambon blanc'),
  ('ingredient', 'jambon cru'),
  ('ingredient', 'jambon serrano'),
  ('ingredient', 'lapin'),
  ('ingredient', 'lard'),
  ('ingredient', 'lardons'),
  ('ingredient', 'magret de canard'),
  ('ingredient', 'merguez'),
  ('ingredient', 'mouton'),
  ('ingredient', 'oie'),
  ('ingredient', 'pancetta'),
  ('ingredient', 'pintade'),
  ('ingredient', 'porc'),
  ('ingredient', 'poulet'),
  ('ingredient', 'rôti de boeuf'),
  ('ingredient', 'saucisse'),
  ('ingredient', 'saucisson'),
  ('ingredient', 'steak haché'),
  ('ingredient', 'veau'),
  ('ingredient', 'anchois'),
  ('ingredient', 'bar'),
  ('ingredient', 'cabillaud'),
  ('ingredient', 'calamar'),
  ('ingredient', 'colin'),
  ('ingredient', 'crabe'),
  ('ingredient', 'crevette'),
  ('ingredient', 'dorade'),
  ('ingredient', 'écrevisse'),
  ('ingredient', 'encornet'),
  ('ingredient', 'espadon'),
  ('ingredient', 'flétan'),
  ('ingredient', 'hareng'),
  ('ingredient', 'homard'),
  ('ingredient', 'huître'),
  ('ingredient', 'langouste'),
  ('ingredient', 'langoustine'),
  ('ingredient', 'lieu'),
  ('ingredient', 'limande'),
  ('ingredient', 'lotte'),
  ('ingredient', 'maquereau'),
  ('ingredient', 'merlan'),
  ('ingredient', 'morue'),
  ('ingredient', 'moule'),
  ('ingredient', 'oursin'),
  ('ingredient', 'palourde'),
  ('ingredient', 'poulpe'),
  ('ingredient', 'raie'),
  ('ingredient', 'rouget'),
  ('ingredient', 'saint-jacques'),
  ('ingredient', 'sardine'),
  ('ingredient', 'saumon'),
  ('ingredient', 'saumon fumé'),
  ('ingredient', 'seiche'),
  ('ingredient', 'sole'),
  ('ingredient', 'thon'),
  ('ingredient', 'truite'),
  ('ingredient', 'beurre'),
  ('ingredient', 'beurre demi-sel'),
  ('ingredient', 'blanc d''oeuf'),
  ('ingredient', 'brie'),
  ('ingredient', 'camembert'),
  ('ingredient', 'chèvre'),
  ('ingredient', 'comté'),
  ('ingredient', 'crème épaisse'),
  ('ingredient', 'crème fraîche'),
  ('ingredient', 'crème fraîche liquide'),
  ('ingredient', 'emmental'),
  ('ingredient', 'faisselle'),
  ('ingredient', 'feta'),
  ('ingredient', 'fromage blanc'),
  ('ingredient', 'fromage de chèvre'),
  ('ingredient', 'fromage râpé'),
  ('ingredient', 'gruyère'),
  ('ingredient', 'jaune d''oeuf'),
  ('ingredient', 'lait'),
  ('ingredient', 'lait concentré'),
  ('ingredient', 'lait de coco'),
  ('ingredient', 'lait d''amande'),
  ('ingredient', 'lait demi-écrémé'),
  ('ingredient', 'lait entier'),
  ('ingredient', 'lait ribot'),
  ('ingredient', 'mascarpone'),
  ('ingredient', 'mozzarella'),
  ('ingredient', 'oeuf'),
  ('ingredient', 'parmesan'),
  ('ingredient', 'petit-suisse'),
  ('ingredient', 'ricotta'),
  ('ingredient', 'roquefort'),
  ('ingredient', 'yaourt'),
  ('ingredient', 'yaourt grec'),
  ('ingredient', 'yaourt nature'),
  ('ingredient', 'avoine'),
  ('ingredient', 'blé'),
  ('ingredient', 'boulgour'),
  ('ingredient', 'couscous'),
  ('ingredient', 'épeautre'),
  ('ingredient', 'farine'),
  ('ingredient', 'farine complète'),
  ('ingredient', 'farine de blé'),
  ('ingredient', 'farine de châtaigne'),
  ('ingredient', 'farine de maïs'),
  ('ingredient', 'farine de riz'),
  ('ingredient', 'farine de sarrasin'),
  ('ingredient', 'flocons d''avoine'),
  ('ingredient', 'fusilli'),
  ('ingredient', 'lasagne'),
  ('ingredient', 'lentilles blondes'),
  ('ingredient', 'lentilles corail'),
  ('ingredient', 'lentilles vertes'),
  ('ingredient', 'linguine'),
  ('ingredient', 'macaroni'),
  ('ingredient', 'nouilles'),
  ('ingredient', 'orge'),
  ('ingredient', 'orge perlé'),
  ('ingredient', 'pain'),
  ('ingredient', 'pain complet'),
  ('ingredient', 'pain de mie'),
  ('ingredient', 'pâtes'),
  ('ingredient', 'penne'),
  ('ingredient', 'pois cassés'),
  ('ingredient', 'pois chiches'),
  ('ingredient', 'quinoa'),
  ('ingredient', 'riz'),
  ('ingredient', 'riz basmati'),
  ('ingredient', 'riz complet'),
  ('ingredient', 'riz rond'),
  ('ingredient', 'sarrasin'),
  ('ingredient', 'semoule'),
  ('ingredient', 'spaghetti'),
  ('ingredient', 'tagliatelles'),
  ('ingredient', 'vermicelle'),
  ('ingredient', 'aneth'),
  ('ingredient', 'anis étoilé'),
  ('ingredient', 'basilic'),
  ('ingredient', 'cannelle'),
  ('ingredient', 'cardamome'),
  ('ingredient', 'cerfeuil'),
  ('ingredient', 'ciboulette'),
  ('ingredient', 'citronnelle'),
  ('ingredient', 'clou de girofle'),
  ('ingredient', 'coriandre'),
  ('ingredient', 'cumin'),
  ('ingredient', 'curcuma'),
  ('ingredient', 'curry'),
  ('ingredient', 'estragon'),
  ('ingredient', 'fenugrec'),
  ('ingredient', 'herbes de Provence'),
  ('ingredient', 'laurier'),
  ('ingredient', 'marjolaine'),
  ('ingredient', 'menthe'),
  ('ingredient', 'muscade'),
  ('ingredient', 'origan'),
  ('ingredient', 'paprika'),
  ('ingredient', 'persil'),
  ('ingredient', 'piment de Cayenne'),
  ('ingredient', 'piment d''Espelette'),
  ('ingredient', 'poivre blanc'),
  ('ingredient', 'poivre noir'),
  ('ingredient', 'poivre rose'),
  ('ingredient', 'quatre-épices'),
  ('ingredient', 'romarin'),
  ('ingredient', 'safran'),
  ('ingredient', 'sarriette'),
  ('ingredient', 'sauge'),
  ('ingredient', 'sel'),
  ('ingredient', 'sel fin'),
  ('ingredient', 'sel de mer'),
  ('ingredient', 'thym'),
  ('ingredient', 'vanille'),
  ('ingredient', 'wasabi'),
  ('ingredient', 'zaatar'),
  ('ingredient', 'bouillon de boeuf'),
  ('ingredient', 'bouillon de légumes'),
  ('ingredient', 'bouillon de poulet'),
  ('ingredient', 'câpres'),
  ('ingredient', 'harissa'),
  ('ingredient', 'huile d''arachide'),
  ('ingredient', 'huile de colza'),
  ('ingredient', 'huile de noix'),
  ('ingredient', 'huile de sésame'),
  ('ingredient', 'huile de tournesol'),
  ('ingredient', 'huile d''olive'),
  ('ingredient', 'ketchup'),
  ('ingredient', 'mayonnaise'),
  ('ingredient', 'miel'),
  ('ingredient', 'moutarde'),
  ('ingredient', 'moutarde à l''ancienne'),
  ('ingredient', 'nuoc-mâm'),
  ('ingredient', 'pesto'),
  ('ingredient', 'sauce barbecue'),
  ('ingredient', 'sauce hoisin'),
  ('ingredient', 'sauce soja'),
  ('ingredient', 'sauce tomate'),
  ('ingredient', 'sauce worcestershire'),
  ('ingredient', 'sirop d''agave'),
  ('ingredient', 'sirop d''érable'),
  ('ingredient', 'tabasco'),
  ('ingredient', 'tahini'),
  ('ingredient', 'vinaigre balsamique'),
  ('ingredient', 'vinaigre blanc'),
  ('ingredient', 'vinaigre de cidre'),
  ('ingredient', 'vinaigre de vin'),
  ('ingredient', 'vinaigrette'),
  ('ingredient', 'amandes'),
  ('ingredient', 'cacahuètes'),
  ('ingredient', 'cacao'),
  ('ingredient', 'chocolat au lait'),
  ('ingredient', 'chocolat blanc'),
  ('ingredient', 'chocolat noir'),
  ('ingredient', 'graines de chia'),
  ('ingredient', 'graines de courge'),
  ('ingredient', 'graines de lin'),
  ('ingredient', 'graines de pavot'),
  ('ingredient', 'graines de sésame'),
  ('ingredient', 'gélatine'),
  ('ingredient', 'levure'),
  ('ingredient', 'levure chimique'),
  ('ingredient', 'levure de boulanger'),
  ('ingredient', 'noisettes'),
  ('ingredient', 'noix'),
  ('ingredient', 'noix de cajou'),
  ('ingredient', 'noix de macadamia'),
  ('ingredient', 'noix de pécan'),
  ('ingredient', 'pignons de pin'),
  ('ingredient', 'pistaches'),
  ('ingredient', 'pâte à tartiner'),
  ('ingredient', 'sucre'),
  ('ingredient', 'sucre glace'),
  ('ingredient', 'sucre roux'),
  ('ingredient', 'sucre vanillé'),
  ('ingredient', 'eau'),
  ('ingredient', 'eau de fleur d''oranger'),
  ('ingredient', 'fécule de maïs'),
  ('ingredient', 'tofu'),
  ('ingredient', 'tofu fumé'),
  ('ingredient', 'seitan'),
  ('ingredient', 'algues nori'),
  ('ingredient', 'agar-agar'),
  ('unit', 'g'),
  ('unit', 'kg'),
  ('unit', 'mg'),
  ('unit', 'ml'),
  ('unit', 'cl'),
  ('unit', 'l'),
  ('unit', 'cuillère à soupe'),
  ('unit', 'cuillère à café'),
  ('unit', 'pincée'),
  ('unit', 'tasse'),
  ('unit', 'verre'),
  ('unit', 'unité'),
  ('unit', 'tranche'),
  ('unit', 'gousse'),
  ('unit', 'botte'),
  ('unit', 'sachet'),
  ('unit', 'feuille'),
  ('unit', 'brin'),
  ('unit', 'boîte'),
  ('unit', 'pot'),
  ('unit', 'au goût')
on conflict (type, name) do nothing;

